### PR TITLE
Few improvements done

### PR DESCRIPTION
**Pull request by gandarez**
Hi guys,
I've added pre-requisites section to Readme.md. Also I cleaned up the code and followed .Net coding conventions.

### CODE REVIEW

**Comment by alanhamlett** [comment]
Thanks!

**Comment by gandarez** [comment]
@alanhamlett please double check why Readme.md is not up to date with modifications done by my commit.

Thanks!

**Comment by alanhamlett** [comment]
It's there, I just moved it to the bottom because Installation is more important for new users:

https://github.com/wakatime/visualstudio-wakatime#contributing

**Comment by gandarez** [comment]
I see. 

Thanks @alanhamlett

**Pull request merged**
