### PR TITLE
Reverted back to Microsoft.VisualStudio.Shell v11

### PR DESCRIPTION
**Pull request by gandarez**
Added support for VS2012 by changing the version o Microsoft.VisualStudio.Shell library. Also added a folder called assemblies to hold all referenced assemblies from Visual Studio.

### CODE REVIEW

**Comment by gandarez** [comment]
Related to #22

**Comment by alanhamlett** [comment]
What are the `assemblies/Microsoft.VisualStudio.Shell.Interop.*.*.dll` files? We should probably add them to the `.gitignore`?

**Comment by gandarez** [comment]
@alanhamlett those assemblies are gonna be hold in that specific folder for who doesn't have for example VS2012 SDK installed as I don't. If you add to .gitignore you'll be preventing it from downloading and probably will break the compilation.

**Comment by alanhamlett** [comment]
Ok got it, thanks!

**Pull request merged**
