### PR TITLE
New way of finding Python executable and other enhancements

### PR DESCRIPTION
**Pull request by gandarez**
Hi guy!

Submitting this pull request I achieved:
- new way of finding Python executable (legacy mode was kept)
- added debug option into SettingsForm
- Added a class to hold all constant values
- other enhancements

### CODE REVIEW

**Comment by alanhamlett** [comment]
Can you re-submit this without bumping the release version? Sorry, it's just better to keep changes separate from version bumps.

Thanks, this looks good otherwise!

**Comment by alanhamlett** [comment]
Nice job using the registry to locate python!

**Comment by gandarez** [comment]
@alanhamlett check it out again.

**Comment by alanhamlett** [comment]
Merged manually. Thanks!

**Comment by gandarez** [comment]
@alanhamlett the next step I'll try to use a 3rd party library to execute Python scripts called Iron Python.

**Comment by alanhamlett** [comment]
Very cool, most problems with WakaTime plugins are related to the Python dependency so including IronPython in the plugin vsix would be a huge improvement!

**Pull request closed without merging**
