### PR TITLE
Visual Studio 2015RC support

### PR DESCRIPTION
**Pull request by davidgabrichidze**
Added NativeMethods class to encapsulate DllImports.
Updated vsix manifest and references to support VS2015RC.
Extension can be installed and used on all editions of VS2013 and VS2015RC.
Solution and project is converted to VS2015RC and built using VS2015RC SDK.

I have already installed it on my VS2015RC and works fine.

### CODE REVIEW

**Comment by alanhamlett** [comment]
This is awesome! I think you forgot to `git add NativeMethods.cs` because I'm getting:

`The name 'NativeMethods' does not exist in the current context`

**Comment by davidgabrichidze** [comment]
Can u try it again? I'm sure it's pushed now

**Comment by alanhamlett** [comment]
Looks good!

**Comment by alanhamlett** [comment]
Thanks!

**Pull request merged**
